[tool.vulture]
min_confidence = 80
paths = ['.']
exclude = ['**/cachedir/*', '**/.venv/*']
sort_by_size = true
verbose = false

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
extend-ignore = "E203"
per-file-ignores = """
    __init__.py:F401
"""

[tool.mypy]
ignore_missing_imports = true
exclude = ["venv", "cachedir", "usr"]

[tool.isort]
profile = "black"
force_single_line = "true"
line_length = 120
